package com.yszoe.sys.entity;

/**
 * EnumColor generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class ApplicationEnum implements java.io.Serializable {

	// Fields

	private String id;

	private String caption;

	/** default constructor */
	public ApplicationEnum() {
	}

	public ApplicationEnum(String id, String caption) {
		super();
		this.id = id;
		this.caption = caption;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCaption() {
		return this.caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

}