package com.yszoe.sys.entity;

import java.util.Date;

/**
 * TSysBizLog generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class TSysBizLog implements java.io.Serializable {

	// Fields

	private String wid;

	private Date czsj;

	private String czdx;

	private String czr;

	private String czlx;
	private String type;
	private String field1;
	private String field2;
	
	private String czms;
	private String cznrzy;
	
	private String czbid;
	private String czrnc;//手动加入，非持久化
	private String czrxxzp;//手动加入，非持久化
	private String nr;//手动加入，非持久化
	private String nrzt;//手动加入，非持久化
	private String hfs;//手动加入，非持久化
	private String czrxb;//手动加入，非持久化
	
	public String getType() {
		return type;
	}
	
	public void setType(String type) {
		this.type = type;
	}

	// Constructors

	public String getHfs() {
		return hfs;
	}

	public void setHfs(String hfs) {
		this.hfs = hfs;
	}

	public String getNrzt() {
		return nrzt;
	}

	public void setNrzt(String nrzt) {
		this.nrzt = nrzt;
	}

	public String getCzrnc() {
		return czrnc;
	}

	public void setCzrnc(String czrnc) {
		this.czrnc = czrnc;
	}

	public String getCzrxxzp() {
		return czrxxzp;
	}

	public void setCzrxxzp(String czrxxzp) {
		this.czrxxzp = czrxxzp;
	}

	public String getNr() {
		return nr;
	}

	public void setNr(String nr) {
		this.nr = nr;
	}

	public String getCzbid() {
		return czbid;
	}

	public void setCzbid(String czbid) {
		this.czbid = czbid;
	}

	/** default constructor */
	public TSysBizLog() {
	}

	/** full constructor */
	public TSysBizLog(String wid, Date czsj, String czdx, String czr,
			String czlx) {
		this.wid = wid;
		this.czsj = czsj;
		this.czdx = czdx;
		this.czr = czr;
		this.czlx = czlx;
	}

	// Property accessors

	public String getWid() {
		return this.wid;
	}

	public void setWid(String wid) {
		this.wid = wid;
	}

	public Date getCzsj() {
		return this.czsj;
	}

	public void setCzsj(Date czsj) {
		this.czsj = czsj;
	}

	public String getCzdx() {
		return this.czdx;
	}

	public void setCzdx(String czdx) {
		this.czdx = czdx;
	}

	public String getCzr() {
		return this.czr;
	}

	public void setCzr(String czr) {
		this.czr = czr;
	}

	public String getCzlx() {
		return this.czlx;
	}

	public void setCzlx(String czlx) {
		this.czlx = czlx;
	}

	public String getField1() {
		return field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	public String getField2() {
		return field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	public String getCzms() {
		return czms;
	}

	public void setCzms(String czms) {
		this.czms = czms;
	}

	public String getCznrzy() {
		return cznrzy;
	}

	public void setCznrzy(String cznrzy) {
		this.cznrzy = cznrzy;
	}

	public String getCzrxb() {
		return czrxb;
	}

	public void setCzrxb(String czrxb) {
		this.czrxb = czrxb;
	}

}