#created on: 2011-4-25
package com.imchooser.gamesrule

#list any import classes here.
import com.imchooser.infoms.entity.biz.TSportBsxm;


#declare global variables buniess service
global com.imchooser.infoms.service.biz.impl.SportCjYdyServiceImpl sportCjYdyService;

/*
即一个区县的所有获得分数的比赛记录，
如果同一场比赛，代表同区县的多人都得分了，那么算一条记录，在得分来源字段记录下多人的编号。
折算得到的成绩因为得分类型不一样，所以不会是同一条记录。
按区县、得分类型 分组。
*/
rule "根据某一场比赛成绩计算出各区县的成绩明细"
	salience 2
	when
		b: TSportBsxm(sfjtxm==1, sfjtxm : sfjtxm)
	then 
		#actions
		
end

/*
即一个代表团的所有获得分数的比赛记录，
如果同一场比赛，代表相同大市（代表团）的多人都得分了，那么算一条记录，在得分来源字段记录下多人的编号。
折算得到的成绩因为得分类型不一样，所以不会是同一条记录。
按地区、得分类型 分组。
*/
rule "根据某一场比赛成绩计算各代表团的成绩明细"
	#include attributes such as "salience" here...
	when
		#conditions
	then 
		#actions
		
end

rule "根据某一场比赛成绩计算21项排名数据"
	//include attributes such as "salience" here...
	when
		#conditions
	then 
		#actions
		
end

/*
即一个区县的所有获得分数的比赛记录，
如果同一场比赛，代表同区县的多人都得分了，那么算一条记录，在得分来源字段记录下多人的编号。
*/
rule "按区县汇总成绩"
	//include attributes such as "salience" here...
	when
		#conditions
	then 
		#actions
		
end

/*
即一个代表团的所有获得分数的比赛记录，
如果同一场比赛，代表同大市（代表团）的多人都得分了，那么算一条记录，在得分来源字段记录下多人的编号。
*/
rule "按代表团汇总成绩"
	#include attributes such as "salience" here...
	when
		#conditions
	then 
		#actions
		
end

