package com.yszoe.sys.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * EnumColor generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
@Entity
public class ApplicationEnum implements java.io.Serializable {

	// Fields

	private String id;

	private String caption;

	/** default constructor */
	public ApplicationEnum() {
	}

	public ApplicationEnum(String id, String caption) {
		super();
		this.id = id;
		this.caption = caption;
	}

	@Id
	@Column(name = "ID", length = 100)
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CAPTION", length = 100)
	public String getCaption() {
		return this.caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

}