package com.imchooser.infoms.entity.sys;

/**
 * TSysCode generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class TSysCode implements java.io.Serializable {

	// Fields

	private String wid;

	private String zdbm;

	private String zdmc;

	private String zdcc;

	private String sjdm;

	private String sfsy;

	private String zdlb;

	private String lbmc;

	// Constructors

	/** default constructor */
	public TSysCode() {
	}

	/** minimal constructor */
	public TSysCode(String wid) {
		this.wid = wid;
	}

	/** huazai's constructor for fieldsManagement! */
	public TSysCode(String zdlb, String lbmc) {
		this.zdlb = zdlb;
		this.lbmc = lbmc;
	}

	/** full constructor */
	public TSysCode(String wid, String zdbm, String zdmc, String zdcc,
			String sjdm, String sfsy, String zdlb, String lbmc) {
		this.wid = wid;
		this.zdbm = zdbm;
		this.zdmc = zdmc;
		this.zdcc = zdcc;
		this.sjdm = sjdm;
		this.sfsy = sfsy;
		this.zdlb = zdlb;
		this.lbmc = lbmc;
	}

	// Property accessors

	public String getWid() {
		return this.wid;
	}

	public void setWid(String wid) {
		this.wid = wid;
	}

	public String getZdbm() {
		return this.zdbm;
	}

	public void setZdbm(String zdbm) {
		this.zdbm = zdbm;
	}

	public String getZdmc() {
		return this.zdmc;
	}

	public void setZdmc(String zdmc) {
		this.zdmc = zdmc;
	}

	public String getZdcc() {
		return this.zdcc;
	}

	public void setZdcc(String zdcc) {
		this.zdcc = zdcc;
	}

	public String getSjdm() {
		return this.sjdm;
	}

	public void setSjdm(String sjdm) {
		this.sjdm = sjdm;
	}

	public String getSfsy() {
		return this.sfsy;
	}

	public void setSfsy(String sfsy) {
		this.sfsy = sfsy;
	}

	public String getZdlb() {
		return this.zdlb;
	}

	public void setZdlb(String zdlb) {
		this.zdlb = zdlb;
	}

	public String getLbmc() {
		return lbmc;
	}

	public void setLbmc(String lbmc) {
		this.lbmc = lbmc;
	}

}