package com.imchooser.infoms.entity.sys;

/**
 * TSysDepart generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class TDepartDetail implements java.io.Serializable {

	// Fields

	private String departid;

	private String linkman;

	private String linktel;

	private String postcode;

	private String address;

	private String fax;

	private String email;

	private String bank1;

	private String account1;

	private String bank2;

	private String account2;

	private String zhmc;

	private String hh;

	private String zhmc2;

	private String hh2;

	public TDepartDetail() {

	}

	public TDepartDetail(String departid, String linkman, String linktel,
			String postcode, String address, String fax, String email,
			String bank1, String account1, String bank2, String account2) {
		this.departid = departid;
		this.linkman = linkman;
		this.linktel = linktel;
		this.postcode = postcode;
		this.address = address;
		this.fax = fax;
		this.email = email;
		this.bank1 = bank1;
		this.account1 = account1;
		this.bank2 = bank2;
		this.account2 = account2;
	}

	public TDepartDetail(String departid, String linkman, String linktel,
			String postcode, String address, String fax, String email,
			String bank1, String account1, String bank2, String account2,
			String zhmc, String hh, String zhmc2, String hh2) {
		this.departid = departid;
		this.linkman = linkman;
		this.linktel = linktel;
		this.postcode = postcode;
		this.address = address;
		this.fax = fax;
		this.email = email;
		this.bank1 = bank1;
		this.account1 = account1;
		this.bank2 = bank2;
		this.account2 = account2;
		this.zhmc = zhmc;
		this.hh = hh;
		this.zhmc2 = zhmc2;
		this.hh2 = hh2;
	}

	public String getDepartid() {
		return departid;
	}

	public void setDepartid(String departid) {
		this.departid = departid;
	}

	public String getLinkman() {
		return linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getLinktel() {
		return linktel;
	}

	public void setLinktel(String linktel) {
		this.linktel = linktel;
	}

	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getBank1() {
		return bank1;
	}

	public void setBank1(String bank1) {
		this.bank1 = bank1;
	}

	public String getAccount1() {
		return account1;
	}

	public void setAccount1(String account1) {
		this.account1 = account1;
	}

	public String getBank2() {
		return bank2;
	}

	public void setBank2(String bank2) {
		this.bank2 = bank2;
	}

	public String getAccount2() {
		return account2;
	}

	public void setAccount2(String account2) {
		this.account2 = account2;
	}

	public String getHh() {
		return hh;
	}

	public void setHh(String hh) {
		this.hh = hh;
	}

	public String getHh2() {
		return hh2;
	}

	public void setHh2(String hh2) {
		this.hh2 = hh2;
	}

	public String getZhmc() {
		return zhmc;
	}

	public void setZhmc(String zhmc) {
		this.zhmc = zhmc;
	}

	public String getZhmc2() {
		return zhmc2;
	}

	public void setZhmc2(String zhmc2) {
		this.zhmc2 = zhmc2;
	}

}