package com.imchooser.infoms.entity.sys;

/**
 * TSysCode generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class TSysCodeSort implements java.io.Serializable {

	// Fields

	private String zdlb;

	private String lbmc;

	// Constructors

	/** default constructor */
	public TSysCodeSort() {
	}

	public TSysCodeSort(String zdlb) {
		super();
		this.zdlb = zdlb;
	}

	public TSysCodeSort(String zdlb, String lbmc) {
		super();
		this.zdlb = zdlb;
		this.lbmc = lbmc;
	}

	public String getLbmc() {
		return lbmc;
	}

	public void setLbmc(String lbmc) {
		this.lbmc = lbmc;
	}

	public String getZdlb() {
		return zdlb;
	}

	public void setZdlb(String zdlb) {
		this.zdlb = zdlb;
	}

}